### ISSUE TITLE
Strange render / capture behaviour with SlotableV2

### ISSUE THREAD

**Issue by Intrepidd** [github/view_component#548]
### Steps to reproduce

- Check out this example repository : https://github.com/Intrepidd/viewcomponentbug-demo
- navigate to /erb and /haml to observe the differences with each templating language

### Expected behavior
The page should properly render as expected, with the header slot content within the H1

### Actual behavior
It looks like the slot content renders straight away then the component layout renders without the slots in erb, and in haml it looks like it's rendered twice : 

```erb
<div>
  <h1>Header: <%= header %></h1>
</div>
```

```erb
Hello World

<div>
  <%= render BlogComponent.new do |c| %>
    <%= c.header do %>
      <%= link_to "My blog", root_path %>
    <% end %>
  <% end %>
</div>
```

Produces : 

![image](https://user-images.githubusercontent.com/803765/101762639-f787fd00-3add-11eb-8fd2-4b1c45916413.png)

```haml
= "Hello world"

%div
  = render BlogComponent.new do |c|
    = c.header do
      = link_to "My blog", root_path

```

Produces : 
![image](https://user-images.githubusercontent.com/803765/101762739-18505280-3ade-11eb-9950-e942f38e9f4a.png)

### System configuration
**Rails version**: 6.1.0 and 6.0.3

**Ruby version**: 2.7.2

**Gem version**:  2.23.0

**Comment by BlakeWilliams** [comment]
@Intrepidd 👋 Thanks for the report! Would it be possible to open a small PR with a failing test?

**Comment by BlakeWilliams** [comment]
This seemed really similar to an issue I saw in the past, so I think I might have a quick fix for it in #550. Thanks for reporting this!

**Comment by Intrepidd** [comment]
Fab ! I confirm your branch fixes my issue 
![image](https://user-images.githubusercontent.com/803765/101791010-5a3fbf80-3b03-11eb-84db-8405d3e82541.png)

Thanks a lot !

**Comment by BlakeWilliams** [comment]
Thanks for confirming! ❤️ 

I just pushed up `2.23.1` with that fix.

**Comment by effkay** [comment]
Unfortunately I am still having the same issue with the most current version of view_component + haml. Any hints? If desired I can re-run the sample project above and post the results.

**Comment by BlakeWilliams** [comment]
@effkay What version of view component are you running into this on?

**Comment by effkay** [comment]
@BlakeWilliams I am still having the issue in 2.24.0. But... I ran the demo app posted above to see if I can reproduce it in there... and once I upgrade to 2.24.0 the issue seems fixed and I can't reproduce it. I'll try to whip up another demo app that reproduces my issue and get back to you.
